language: go

go:
  - 1.14

service:
 - docker

sudo: required

before_install:
    - git clone https://github.com/diodechain/cross-compile.git
    - cd cross-compile/pi-zero
    - docker image build -t crosscompile:0.1 .
    - cd ../..

install:
  - make diode

before_script: make lint

script:
  - make test
  # test build on pi
  - docker container run -v  "${PWD}:/build" crosscompile:0.1 go build -tags openssl_static_pi cmd/diode/*.go

env:
  - GO111MODULE=on
